version: '2'
services:
  db:
    image: "neo4j:3.0"
    ports:
      - "7474:7474"
    environment:
      - NEO4J_AUTH=neo4j/Password12
      - NEO4J_dbms_memory_pagecache_size=128M
      - NEO4J_dbms_memory_heap_maxSize=256
  platformer:
    build: ../the-platformer
    networks:
      - rawhat
    ports:
      - "8002:8002"
    volumes:
      - "../the-platformer:/usr/src/app"
      - /usr/src/app/node_modules
    depends_on:
      - db
  playlistr:
    build: ../playlistr
    networks:
      - rawhat
    ports:
      - "4000:4000"
      - "8080:8080"
    environment:
      - MIX_ENV=dev
      - PORT=4000
    depends_on:
      - db
  enjoychess:
    build: ../enjoychess
    networks:
      - rawhat
    ports:
      - "8001:8001"
    volumes:
      - "../enjoychess:/usr/src/app"
  rawhat_net:
    build: .
    networks:
      - rawhat
    ports:
      - "3000:3000"
  nginx:
    build:
      context: .
      dockerfile: nginx-Dockerfile
    depends_on:
      - platformer
      - playlistr
      - enjoychess
      - rawhat_net
    networks:
      - rawhat
    ports:
      - "80:80"
networks:
  rawhat:
