version: '2'
services:
  db:
    image: "neo4j:3.0"
    ports:
      - "7474:7474"
    environment:
      - NEO4J_AUTH=neo4j/Password12
  platformer:
    build: ../the-platformer
    ports:
      - "8002:8002"
    volumes:
      - "../the-platformer:/usr/src/app"
    depends_on:
      - db
  playlistr:
    build: ../playlistr
    ports:
      - "4000:4000"
      - "8080:8080"
    environment:
      - MIX_ENV=dev
      - PORT=4000
    depends_on:
      - db
  enjoychess:
    build: ../enjoychess
    ports:
      - "8001:8001"
    volumes:
      - "../enjoychess:/usr/src/app"
  rawhat_net:
    build: .
    ports:
      - "3000:3000"
  nginx:
    build:
      context: .
      dockerfile: nginx-Dockerfile
    ports:
      - "80:80"
